name: CI

on: [push, pull_request]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: C++ Tests
        run: .\scripts\cpp_tests.bat
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: C++ Tests
        run: ./scripts/cpp_tests.sh
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: C++ Tests
        run: ./scripts/cpp_tests.sh
